# Generated by Django 4.2.11 on 2024-04-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0004_alter_note_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
