# Generated by Django 4.2.11 on 2024-04-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuss',
            },
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='to_do_list.status'),
        ),
    ]
